# Generated by Django 3.1.5 on 2021-01-07 21:53

from django.db import migrations

def create_categories(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Genre = apps.get_model('games', 'GenreCategory')
    genre = Genre(name="word", description_short="word", description_long="word")
    genre.save()
    genre = Genre(name="strategy", description_short="strategy", description_long="strategy")
    genre.save()
    genre = Genre(name="team", description_short="team", description_long="team")
    genre.save()
    genre = Genre(name="quiz", description_short="quiz", description_long="quiz")
    genre.save()
    genre = Genre(name="trivia", description_short="trivia", description_long="trivia")
    genre.save()
    genre = Genre(name="loud", description_short="loud", description_long="loud")
    genre.save()
    genre = Genre(name="solo", description_short="solo", description_long="solo")
    genre.save()

class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]
