# Generated by Django 3.1.5 on 2021-01-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players_max',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
