# Generated by Django 3.1.5 on 2021-01-07 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_players_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players_max',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='players_min',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
